name: Run lint and static analyis checks
on:
  pull_request:

concurrency:
  group: lint-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: plus3it/actions-workflows/.github/workflows/lint.yml@09879910a1e194e51e7407474ecdb0836ed01de1
